### PR TITLE
Comment workflow

### PR DESCRIPTION
**Pull request by vpnarea**
Change-type: patch

### CODE REVIEW

**Comment by vpnarea** [comment]
@klutchell I've set up a test with an unrelated GitHub account opening a PR on my fork of Flowzone. The `pull_request_target` event does not require approval and runs automatically. The `pull_request` requires approval:

image

**Comment by ab77** [comment]
@klutchell I've confirmed `pull_request_target` always requires approval (with every commit and sync).

**Comment by klutchell** [comment]
Perfect, so if we roll out the new flowzone template described [here](https://github.com/product-os/flowzone/pull/333/files) we will likely never see approval requests because internal PRs don't need it and external PRs will use PRT that don't require approval since protection is included.

**Comment by ab77** [comment]
> .. we will likely never see approval requests because internal PRs don't need it and external PRs will use PRT that don't require approval since protection is included.

we will probably get a question though - "why aren't my changes being tested".

**Comment by klutchell** [comment]
> we will probably get a question though - "why aren't my changes being tested".

@ab77 Will we? I think we ensured that the workflow will always run, either via PR or PRT, and if an external contributor changes something they shouldn't [they will get a notice](https://github.com/product-os/flowzone/pull/336).

I can't think of any situation where changes are made and something unexpected happens without a notice?

**Comment by ab77** [comment]
@klutchell I missed that, We are probably covered for now. We should test this as soon as it's merged, by doing a couple of external contributions from non-balena affiliated accounts. I have one I can use.

**Comment by klutchell** [comment]
We should see if our security team wants to do some pen testing and see if
they find anything we missed...

**Pull request closed without merging**
